exports.getRashifalData = () => {
  return {
    rashifals: [
      {
        name: "Aries",
        asName: "মেষ",
        imageUrl: "aries.png",
        physicalAppearence:
          "Persons born under Aries sign possess lean and muscular body, middle stature, neither thick nor stout, rudy complexion, long face and neck, broad head at the temples and narrow at the chin. Thin features, mark or scar on head or temples, bushy eye brow, rough or wiry hair varying in colour from dark to sandy, sometimes going bald. Eyes grey to grey-ish brown.",
        mentalTendencies:
          "Ambitious, activity, courage, energy, enterprise, impulsiveness and ingenuity. Love to be independent.",
        personality:
          "Aries born persons are ambitious, rash in temper and of aggressive nature. They are of simple, frank and of outspoken nature, well-disposed and capable of holding command in executive positions. They are not good in organising schemes, but they can guide, control and govern themselves or others. Lover of independence, brave, venturesome, generous, to some extent extravagant. Also well informed, ingenious, zealous, and dogmatic in their opinions; remarkable for sudden changes and quick action and have progressive tendency. Life will be full of struggle and fortune is variable. Ardent in politics and religion. Travelling in life is imminent. Relatives are not favourable and the family ties are sometimes strained, frequent changes in residence, having a few children. They marry early and in a hurry. Legal proceedings in life may follow him. Residence in foreign land under forced circumstances. There will be no dearth of enemies but you will be conqueror of them. Somewhat fiery or quick tempered. They will succeed best in vocations requiring quick action, decision, executive or mechanical ability and responsibility.",
        health:
          "Generally Arians enjoy good health and have power of resistance or the diseases. They are prone to minor injuries and serious accidents particularly to the head. So they should avoid rash driving. Arians are liable to suffer headaches, burns, inflammatory diseases, brain affliction, colic pains, high fever, pimples, paralysis, insomnia and small pox etc. Aries denotes skull bones and face except nasal. Also indicates muscles like occipital, departments articularm, buccinator, internal carotids, temporal carotids and head etc.",
        cautions:
          "Arians should take plenty of rest and sleep. Green vegetables and good food is must for them. They should relax, control their feelings, avoid worry, excitement and anger. They should avoid stimulants and non-vegetarian meals.",
        finances:
          "Arians are not meant for amassing wealth inspire of their strong desires. Extravagance should be avoided. They lose money through impulsive actions and rash investments. Evil planets if posited in Aries indicate that they start in a flash and end in a crash, their budget always remain as unbalanced. They should think calmly and seriously before any action.",
        loveAndMarriage:
          "Arians are extremely frank and enthusiastic in love, their good nature and charm attract the opposite sex. They are of practical views, desire lasting affection, freedom and adventure in love are their basic traits. Arians should soften their dominant nature, to be happy and should not be impatient and emotional. They should stick to old lovers rather to change.",
        husbands:
          "Such persons are very desirable partners, usually they select beautiful, clever and good wives. Generous and bountiful, romantic but spendthrift. Rash and passionate.",
        idealMatch:
          "Leo, Libra and Sagittarius born persons are fit to marry Arians. But they should try to be peaceful, avoid lavish spending, rash temperament and have saving disposition.",
        domesticEnviornments:
          "A good neat and clean house. Good friends and excellent hosts. Love their home and family. Good company and many friends are the weakness of Arians and they are of cheerful nature. In order to have a happy home, they should avoid rash temperament, criticism of each other and should not to be impulsive, impatient, sarcastic and revengeful.",
        professions:
          "Professions ruled by Mars best suit Arians. If the planet which denotes one's profession by owning either 2nd, 6th or 10th house in one's horoscope, occupies Aries in Rashi or lord of the house occupies, in Navamsa, if Aries happens to be the 2nd, 6th or 10th house and lord Mars is very strong, professions connected with Army, Defence Department, Surgeons, Police, Chemist, Law, Iron and Steel, Machines, Factories, industry or sports goods are best suited for them.",
        lucky:
          "Lucky days for Arian born people are Tuesday, Saturdays and Fridays, Monday and Sunday are fair. Other days are expensive and undesirable. Day of fast is Tuesday. Lucky numbers are 9 and 1, attractive 4 and 8. Passive numbers are 2, 3, 5 and disagreeable numbers are 6 and 7. Favourable colours are Red, Yellow, Copper and Golden. Use of black colour is to be avoided.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        weakness: "N/A",
        traits: "N/A",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Taurus",
        asName: "(বৃষ)",
        imageUrl: "taurus.png",
        physicalAppearence:
          "The person born with Taurus as rising sign at the Ascendant are of short to middle height of broad forehead, bright eyes, thick and stout neck, dark hairs, clear complexion, well developed body, ambitious and obstinate.",
        mentalTendencies:
          "Persevering, constant, conservative determined, obstinate and ambitious of power yet social, affectionate and loving but can also be very unreasonable at times, prejudiced, when angry will not stop at anything. Are slow but good and steady worker.",
        personality:
          "Taurians are enduring and very patient, violent and unrelenting. They are slow and steady and are possessed of strong Will, domestic and determined. Anything done is well done and thought beforehand. Can work hard, when opposed they become stubborn and unyielding. Usually are secretive and reserved, sincere, reliable and trustworthy. They are fond of pleasure and love, natural beauty, art, music and literature, Sympathetic having a magnetic quality. They have the ability to earn and are good for executive jobs. They become worldly and lead a pleasurable life. Fond of ease, comfort, opposite sex and will have many love affairs. They will on the whole enjoy a good health. One can depend or their opinion, ever smiling but highly diplomatic. The planetary signifier is Venus.",
        health:
          "Taurians possess normally robust and super-human health, less sensitive to pains. They suffer from an overabundance of life, will never admit physical disability. It they fall ill, suffer from a long time as their recuperative power is not satisfactory and recovery is slow. Generally Taurians are prone to affliction of throat, tonsils, diphtheria, neck, pyorrhea, cold and apoplexy. Pimples and eyesores give them troubles. The most sensitive part is throat for which a great care be taken. As age advances, one may suffer from constipation, plethora and similar difficulties. They have unbounded appetite and try to lead temperate life.",
        cautions: "N/A",
        finances:
          "Such persons have saving nature, will accumulate and hoard money and never squander unnecessarily. Gambling nature is also indicated and will gain during Mercury period. Patience and perseverance is the basic nature. Are of materialistic mind, will get money from others. Practical and rise gradually, they do not take chances, absolutely not extravagant but save always and do not risk money. They know the value of money and never waste.",
        loveAndMarriage:
          "Venus is lord of Taurus sign. It indicate, love affairs, taste in music, art, cinema and drama etc. Taurians are may be opposition and upsetting conditions. They should have self-control. They are not impulsive in love, and take a long time in selecting partner in life. Faithful in love with deep emotion, do not like quarrels and hate confusion. They respond well to kind treatment and are flattered by luxury. They will always fulfil their social and financial obligations. In married life they are well set, men will have loving wives and ladies devoted husbands. Divorce is rare. They will bear and suffer the untold miseries and never desert the partner. They will shelter the partner, well looked after, attended upon, cared for and protected under any circumstances. They are fond of giving parties, sumptuous food to others and hope to be treated by others in similar ways.",
        husbands:
          "Taurians husbands devoted to their wives and adore them, they are reliable, generous and faithful. They never neglect the house and needs of the partner. The husband likes to see his wife well dressed, attractive and pleasing. Co-operative to the maximum in the domestic sphere and love the partner extensively.",
        idealMatch:
          "Taurus born people are best suited for Virgo, Capricorn, Cancer, Scorpio and Pisces. The matches between them will indicate good partners, contributing to peace, maintaining harmony and leading a happy life.",
        domesticEnviornments:
          "A happy and harmonious domestic atmosphere. The life will be good and prosperous. Good and devoted husband and a happy, home and loving wife. They have comfort, rest and peace at home.An orderly and decorated home, a tidy and good maintenance of house and furniture etc. Peace, pleasure, property, prosperity, popularity and position means much to them. ",
        professions:
          "Taurians like to trade in luxury goods, cosmetics, scents, jewels and gems etc. Any business connected with finance, agriculture, music, pleasure resorts, cinema, actors, film producers etc. transport business, I.T. Department, Ladies clubs and schools, fashion and beauty parlours etc. dealer in ladies garments and beauty items will be a source of success.",
        lucky:
          "The numbers vibrate with them are 2 and 8, attractive to them are 7 and 9, passive numbers are 1,3,4 and 6, whereas number 5 will disagree. Friday, Wednesday, Saturday and Monday are the favourable days. Thursday indicates gain through partner. Tuesday denotes extravagant expenses. Sunday should be a day of rest at home. Day of fast is Friday. The best suited colours are Pink, Green and White. Avoid use of Red colour. Lucky stones are Diamond, Sapphire and Emerald in Gold or Platinum which should be worn in 3rd finger of right hand on Friday morning after performing prayers. When the lord Venus is in fall or unfavourable, one should use white coral or white sapphire to mitigate the evil effects.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        weakness: "N/A",
        traits: "N/A",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Gemini ",
        asName: "মিথুন",
        imageUrl: "gemini.png",
        physicalAppearence:
          "Gemini born persons are tall, upright, slender, quick. Lovely and quick witted, sometimes shy or retiring humane, good disposition, but nervous and restless. Admirer of music, dance, drawing, painting, travel and inventions.",
        mentalTendencies:
          "Quick in grasping, learning and acquiring a good education. Lovely and quick witted, sometimes shy or retiring humane, good disposition, but nervous and restless. Admirer of music, dance, drawing, painting, travel and inventions.",
        personality:
          "No one can do better things successfully and gracefully than Geminians, but the weakness is, they should have deliberate determination to do their work and stick to its completion. They lack concentration and quick decision. They are ambitious, aspiring, curious to know the results of their efforts immediately. Argumentative, engaged in two or more pursuits at a time.<br/>Fond of mental recreations. At times they are restless, anxious, highly strung and diffusive, mentally timid, indecisive and excitable. Love, change and diversity in all spheres to life. They are good advisors and can be relied only in the case of emergency. They are very clever as they are progressive, energetic, inventive, mechanical, ingenious and have retentive power. They refuse to be bound by rules. Geminians can prove good detectives, journalists and an excellent schemer. If Mercury is retrograde at birth, they will prefer to side-step the truth and enjoy a good joke. They are subject to lot of changes in their life. Enjoy the life to the maximum and suffer continuous misfortunes under the influence of opposite sex and disagreement with the father and family disputes arise. Troubles from progeny. Capable of making friendship very quickly but such relations die due to their fault finding nature. The more the romance, more happy they will be. They should only marry with person born in Libra, Aquarius, Aries and Leo having as their ascendants. The planetary signifier is Mercury.",
        weakness:
          "The Geminians lack in concentration and quick decision. They should not give themselves unto a petty strife. Always hasty and anxious to know the results of their efforts then and there. They want only short cuts, are able to carry out work quickly adopting improved methods. Events will move faster in their life than others. They should give up curious traits hastening others Advice. They should take rest, take plenty of exercise, fresh air breathing, eat conservatively and cultivate physical and mental peace.",
        health:
          "Geminians spoil their health through unnecessary and unavoidable worry and anxiety. So they should avoid mental strain, their health will be normally good. Do not overtax yourself by large variety or overwork. By rest and good sleep he can maintain his health. Gemini rules over lungs, shoulders and Arms. Pulmonary affections, cold running of nose, influenza, pleurisy, bronchitis, T.B. all are the possible diseases which can afflict him. When Gemini is afflicted defects in shoulders and arms is indicated. Piles, fistula, bladder and kidney afflictions are also denoted.",
        cautions: "N/A",
        finances:
          "There will be lot of changes in their life. They will enjoy the life with a good fortune and suffer continuous misfortune experiencing both privation and plenty. Family disputes and disagreement with father. They will bring their downfall themselves by their secret love affairs if Mars, Saturn and Venus afflict they also contribute and such attachments will bring loss and difficulties. Some may have progeny through such connections which will be perennial source of trouble and headache to them.",
        loveAndMarriage:
          "Gemini is a dual sign, so the natives will feel that variety is the spice of life. They make quick friendship and find fault quickly and often lose them, so they cannot find a friend to their satisfaction even though they long for it. They cannot be understood easily but romance for them is the source of most happiness. Their affection is controlled by the mind than by the emotions. They are calculating and cynical in love. They are flirts by nature. In case the partner of Geminian is equally intelligent they will enjoy the married life otherwise bickering and separation may follow. Many short journeys in life are indicated.",
        husbands:
          "Such persons want 'Yes Wife'. The partners should not take their flirtations seriously if they want peace and harmony at home. Such people can put an abrupt end to the romance if they feel, it is a source of expense and loss, and cannot tolerate overbearing wives and may leave home as they are unable to put up with constant pressure for the partner.",
        idealMatch:
          "Geminians are best suited for Libra, Aquarius, Aries and Leo born people. These combination can lead to happy and favourable life. ",
        domesticEnviornments:
          "Geminians feel delight in entertaining business partners, friends, relatives and customers. They are a bit extravagant. Keen for keeping the home at a medium level. They often change their residence. Being Mercurians they cannot remain idle mentally or physically. Generally they are fair. Quite hospitable and generally of adjusting nature. Though fond of children yet give less parental care and need careful handling.",
        professions:
          "Geminians have interest in varied jobs as they are active, alert and industrious. As they are intelligent, humorous, and good speakers and will come eventually before the public. So the best professions for them are brokers, intelligent agents, successful businessman, secretaries and efficient advocates. A good convincing power in one of their attributes and may lead in journalism. They like to travel from place to place and have varied professions and are successful travelling agents and jobs Connected with it.<br/>They can find ways and new methods of earnings and will have dual source of income in life. But they are advised to be more economical as they will be having a regular income.",
        lucky:
          "Monday, Thursday, Wednesday and Friday are favourable days, Tuesday and Saturday are days of worries, difficulties and loss. Sunday good for short journeys and routine work. The vibrated numbers are 7 and 3, attractive 5, 6 and 9, positive numbers are 1, 2 whereas disagree numbers are 4 and 8. Lucky and favourable colours are yellow, purple, blue, green and pink, Avoid red and black. Day of fast is full Moon day. Lucky stones are Emerald and Yellow Sapphire which should be used in Gold of 3, 5, 7 or 10 Carats in 4th finger of right hand on Wednesday morning after offering prayers. But when Mercury is unfavourable or in fall, one should use emerald and Ruby in Gold to reduce or mitigate the evil effects.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits: "N/A",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Cancer",
        asName: "কৰ্কট",
        imageUrl: "cancer.png",
        physicalAppearence:
          "Not usually above average height, tendency to stoutness, sometimes awkward and walk with a rolling gait. Round face, full cheeks, tendency to double chin. Short nose but sometimes prominent at the tip. Grey or light blue eyes, pale complexion, wide chest and small hands and feet.",
        mentalTendencies:
          "Cancerians are fond of change, novelty and travelling. Attached to relatives and home, inclined to public life, sympathetic, changeful and impatient. Sentimental, sympathetic, emotional and over sensitive. Anger comes and goes quickly. Diplomatic, discreet and conventional.",
        personality:
          "Changeable, ups and downs of positions and occupations in life. Of fertile imagination, sentimental, sympathetic and talkative. They are timid to face physical danger but are brave. Their temper is changeable. They have tenacious memory, and are industrious, emotional and conventional. They have strong emotional nature and are romantic, they also have psychic medium faculty. They have changeable nature. In love affairs they love intensely and have a nature of true hospitality. Of fiscal mind and have deep feelings of loyalty and responsibility. Cancerians are more interested to obtain small sums of money from different sources than a big amount, from one source. They are secretive, impressionable and magnetic. They should not be impatient, changeability and indolence are the other weakness. Health will be fragile in youth but will improve as age advances. Cancerians can be afflicted for lungs, flu, cough, asthma, bronchitis, tuberculosis and dyspepsia etc. Best suited for commercial career, they cannot tolerate dishonesty in business etc. They accumulate wealth by dint of their own hard efforts. Good husbands and wives are born in Cancer ascendant. They are devoted to domestic life, to husbands, to wives sincere and sympathetic. Cancerians can sacrifice all for their children.",
        weakness: "N/A",
        health:
          "Cancerians have fragile health in youth but as age advances they will pick up the health. Cancer rules chest and stomach. Nervous and worried. Digestive system and throat is to be taken care of. They should not be worring and should have a reasonable diet without alcohol. Guard against asthma, gastric problems, week digestion, rheumatism and sciatica. Diseases which can afflict Cancerians are afflictions of lungs, throat, flu, cough, pleurisy, dyspepsia, flatulence, nervousness, fear complex, hysteria, bile, gall stone, worms and boils on the chest.",
        cautions: "N/A",
        finances:
          "Cancerians are very careful for the money, being honest themselves, they cannot tolerate any dishonesty and are not extravagant. As Jupiter is exalted in this sign, they accumulate wealth through their own hard labour. They are fortunate in finances.",
        loveAndMarriage:
          "Monotonous life without romance for Cancer born people, loyal sincere and affectionate in love, but they lack in expressing their loyalty and sincerity to the partners. They are honest and very true. They are stubborn and determined but also fickle minded and changeable. Cancer born people love their home, family and enjoy a settled family life. A good homely being in general but of romantic and passionate in nature. They make good parents for children, for them they will sacrifice their own needs and will provide education and all comforts to their children. Their children will also remain grateful, obedient and dutiful. Gain through children, in spite of the fact that their children will be frank and will not tolerate any imposition upon them, full of heroism, cool and calm minded, collected and sharp.",
        husbands:
          "Cancer born husbands are devoted to their wives. They would like to marry a homely girl, keep their wives cheerful, pleasing her in every way. Such persons are often dissatisfied and will be indulging in criticism in one way or the other and may interfere in routine household matters and create unpleasant atmosphere, which attitude should be avoided by them. Cancerians are open and frank at sight, but in reality they hide much from each other’s. They are impressionable and magnetic. Sensitive and retiring, romantic and imaginative. Easily influenced and will adjust to circumstances.",
        idealMatch:
          "Cancer born persons should preferably marry Cancerians, Scorpio or Pisces born persons. ",
        domesticEnviornments:
          "Cancer born are devoted to their family. They love the home, and derive pleasure. Fond of collecting antiquities, constant journeys but even they keep home comfortable. A good family atmosphere, attend to their friends, host them to their full satisfaction. Love of home and children are their basic instinct. They desire to keep friendship on long standing basis. A good homely atmosphere prevails generally.",
        professions:
          "Cancerians have commercial career and in things derived from water, conches, pearl, fish etc. May be sailors, in Navy, submarine, shipping departments, import or export, transport and travels. Also a good caterer, restaurant managers, orators, preachers, contractor or any good job in irrigation department. Interested in developing Vedic and sacred texts. <br/>Traits to be Corrected. Cancerians should be patient, endured and avoid sensitiveness. Indolence and changeability are their weak points and needs to be corrected. Be a practical hand, avoid inferiority complex and should not be over anxious, lazy and passive. They should control their emotions and develop spiritual side, should not be vindictive. They should overcome their timid nature and do not be very sensitive and extremely selfish whereas patience and endurance should be cultivated.",
        lucky:
          "Sunday and Fridays are favourable for enjoyment and pleasure. Monday, Tuesday and Thursdays are days of success. Wednesday is good for journey and investments. But Saturday is an unfavourable day and may create disharmony, dispute, difference of opinions, delay in efforts, etc. Lucky Colours are white, cream, red and yellow. But blue and green should be avoided. Lucky numbers Most vibrated numbers are 4,6, whereas attracted numbers are 8 and 1. Passive numbers are 2,7,9, and numbers which will disagree and are to be avoided are 3 and 5.Lucky Stone. For Cancer born pearl in silver be used in 4th finger on Monday morning after offering prayers. But when Moon is afflicted, unfavourable or in fall one should use yellow sapphire plus pearl. These Gems be worn during bright nights. The day of fast is Monday.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits: "N/A",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Leo",
        asName: "সিংহ",
        imageUrl: "leo.png",
        physicalAppearence:
          "Leonians have broad shoulders, ruddy or florid complexion, large bones and muscles. Tall, upright upper body better formed than lower. Thin waste, prominent knees. Soft and wavy hair usually light in colour with tendency to baldness. Head full sized and round. Full stature and majestic appearance, imposing, commanding and dignified. Broadly complexion will vary according to their planets in and assenting the Ascendant. He will be tall, well-built and muscular Grey, catching and large staring eyes. In short a royal disposition.",
        mentalTendencies:
          "Ambitious, generous, honourable, frank warm hearted, self-confident, fearless, impulsive, determined, preserving and conscientious. Fond of power and distinction. Has a liking for art, cheerful, optimistic disposition. Magnanimous and generous. Large hearted and noble but harsh in temperament.",
        personality:
          "Good nature, philosophical, frank, free and outspoken, strong Willed, independent, forceful and impulsive, inspiring, they have great hope. Helpful to mankind and other creations of God. Of wise judgement. They always forgive others and forget the mistakes, sins, and errors of others, Very independent in views, have excellent organising powers, they are constructive, inventive, magnanimous and ingenious. They are subject to flattery but do not fall victim to it. Being a fiery sign Leonian are ambitious, hopeful to the last minute, brilliant, boasting clever actions, commanding, domineering, enthusiastic, joyous and jubilation. They are good planners, leaders and have vitality and vigour. Of rash temperament but their outbursts do not last long. Brave, constant in love and relations and helpful to everybody. But they are generally teased by opponents and enemies whom they face bravely and with courage and confidence. Over liberal and extrovert. They are hasty and become irritated, they arrive at forcing and hasty conclusion and suffer. They have generally robust health. For good health and temperate living and balanced diet is absolutely necessary.",
        weakness: "N/A",
        health:
          "Leonians generally keep a good and splendid health. In case they fall ill, they tend to recover rapidly from any illness. But they are easily alarmed whenever sickness overtakes them. Leo indicates heart, the spinal column, column, spinal marrow, nerves, fibre, bone, intestinal muscles, anterior and posterior coronary. So heart disease, palpitation of heart, spinal meningitis, sun stroke, giddiness, inflammations, epilepsy, rheumatic fever are the diseases indicated for this sign. When Aquarius and Capricorn and afflicted or posited with malefic planets, may cause swelling the ankle followed by heart disease. Jupiter in Leo or assenting Leo will protect one from surgical operation etc. but if Mars afflicts Leo it will indicate surgical operations etc.So in order to keep good health and particularly to avoid heart affliction one should take balanced diet, avoid drinks, stimulants and beverages etc. In other words Leonians should have ‘Sawt-vic’ diet.",
        cautions: "N/A",
        finances:
          "Leonians are generally fortunate and have sufficient resources. They are spendthrifts; their bank position will be deteriorating as age advances. They are tempted to gambling and speculation but they are luckily rewarded, they should avoid this. As they are liberal and do not hesitate to assist anybody, rather feel proud and pleasure past them at a loss and in trouble in old age, so they should control this habit. Leonians often occupy a position of trust and authority. They try to deal with large issues and leave the minor details to their subordinates. Actually they are born rulers. The author would like to warn Leonians to save for the old age due to the fact that their lavish spending nature may face financial troubles as age advances from youth onwards.",
        loveAndMarriage:
          "Leonians are romantic, an ideal lover, fiery in passions but sincere and faithful in love. But they will not show any demonstration of love in public as they consider it below their dignity. Leonian will have great affection to the opposite sex and remain in the crowd of ladies, so the partner should not be jealous of them but have proper understanding rather than doubting each other. They maintain harmony in domestic life unless the 7th house or lord thereof is afflicted, then there will be bickering’s between the partners. They will love their children most, and feel very proud of them. Children will be of independent views, dislike restrictions and may become nervous and restless. So Leo people should relief on their children otherwise they may lose their confidence. Their children will be good organisers, not arrogant, popular, good natured, obliging and affectionate also courageous and confident if they are also born in Leo. But this does not mean that children born in other signs will not have upper qualities, their characteristic will be governed by the sign in which they are born.",
        husbands: "N/A",
        idealMatch:
          "Leo is a fiery sign and are best suited for Aries and Sagittarius other two fiery signs and the three Airy signs, Gemini, Libra or Aquarius born people for more compatibility. Aries and Sagittarius born will contribute full happiness and harmony. Aquarius born are devoted to Leo, Libra born will ever try for company, avoid troubles and purchase peace at any time. One born in Gemini will be very tactful, inseparable, sincere and affectionate. One always tries to please the partner. A Leo bride marrying Aries husband is lucky, as she has a commanding person so that she will know her limits and will not overstep in exercising her authority or spending lavishly.",
        domesticEnviornments:
          "Since Leonians are born to rule, so they will try to be leader in the house and expect all those to be a home to be submissive, cooperative, obedient and grateful to him. They like the family members to be magnanimous and noble. they try to keep peace, harmony and happiness all these will keep him cheerful. The health needs relaxation. They will keep home tidy, decorative and attractive. Careful and choosy for dress, furniture, curtains etc. They are very choosy for their friends, and entertain them often. They never hesitate to spend money to keep their prestige and honour, not economical even in the state of poverty. They will lead an aristocratic life and their home will be an impressive one.",
        professions:
          "Leo born famous and high position in commerce or in government. They will have fixed income, security of job, and it gives executive ability and tireless working capacity. One will be best suited as manager of the big concerns, corporation or director, caption, sales manager etc. Planets forming favourable aspects specify the nature of profession.",
        lucky:
          "Sundays, Tuesday, Wednesday, Thursday and Friday are favourable days whereas Monday, Saturdays of the week be avoided for important works and staring new ventures. Lucky numbers. The numbers 1,4,5,9 and 6 are lucky, avoid 2,7 and 8 whereas passive number is 3.Lucky colours. Orange, Red and Green. Avoid Blue, White and Black. Lucky Stones. Ruby or Emerald in gold be used in 3rd finger of right hand on Sunday morning after prayers. When Sun is afflicted, unfavourable or in fall, one should use Ruby plus Red Coral or Ruby plus Emerald in Gold. To reduce the evils, keep fast on full Moon days regularly throughout your life.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "Since Leonians are determined and of dogmatic views they should take other's views, ideas and suggestions before deciding any issue. Leonians are extroverts, roar like a lion and get into trouble, which temperament should be avoided, specially during the sub period of the evil planet which afflicts Sun, any argumentative nature, altercations and actions annoying superiors be avoided, they should not be hasty and get irritated. Leonians should avoid forcing their desires and opinions on others, should be never arrogant, restrict their wants, should take lessons from the past, behave in a attractive manner, be economical for the old age and maintain bank position. Avoid rash temperament and impulsiveness. Be patient, careful do not be carried away by other, flattery and on top of all they should remain more detached from feelings.",
        ladies:
          "Such ladies are ambitious and ideal, manages her home ideally, successful social worker and make favourable impressions on all. She will command social and prominent position, is a self-sacrificing and has an everlasting love. A Leo born lady need not doubt her Leo born husband for being popular in opposite sex, not selfish and does not expect return from others for having done good to them. Leo born ladies need one to keep her under control so that she can appreciate her husband's good nature, affection, kindness and real love to lead a pleasant, prosperous and peaceful life. They are very passionate and require self sex control lest they go beyond limits, are of fixed ideas, dogmatic views and expect that their word should be law in the home.",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Virgo",
        asName: "কন্যা",
        imageUrl: "vigro.png",
        physicalAppearence:
          "Virgos are tall with a slander body. Dark and hairy. Curved and hairy eyebrows, thin and shrill voice, walks quickly and will never have a pot- belly. Straight nose, appear younger than age, a pronounced forehead, frank and honest expressions of the eyes and sometimes beautiful blue eyes (Venus is the ruler of the second house). Complexion will be as per ascendant and aspects on the same.",
        mentalTendencies:
          "Fond of learning, active mind, good mental abilities, critical, methodical, ingenious, undecided but usually precise though nervous and lacking self-confidence. Perceptive and somewhat intuitive, critical, keeps things properly and orderly and thinks in a methodical way. A genius, analytical and a deep thinker.",
        personality:
          "Virgos are ambitious for wealth, are conservative, modest, thoughtful, contemplative and industrious. They have good endurance not easily contented, changeable nature and environment, often change their residence. They have commercial instinct, methodical, practical and discriminative. Experts in finding faults with others. Best suited for the post of inspector, auditor, income tax officer of examiner. A saving disposition, over careful and sensitive. Love details of things and accounts. Speculative, cautious regarding their own interest, diplomatic, delight in horticulture, intellectual and economical. Prudent, act with fore-thought, fond of studying science particularly about medicine, food, diet, hygiene etc.<br/>They should avoid drugs, should not be talkative, avoid criticism changeability, first think, then decide and to it, do not be fickle minded. Should develop a true consistency of purpose. He should learn to forget other's mistakes and forgive them for their faults. They should not be revengeful. To maintain the health, care for diet should be taken, he will enjoy robust health with long life and healthy old age. Keep his stomach and nervous system in order, take vitamin B and have a balanced diet. They are prone to the diseases of bowls, abdomen and nervous disorder.<br/>As regards finances, they have a commercial and business instinct. Will succeed in matters connected with the earth and its products. He will face many ups and downs in life, hard work will pay. Methodical, have wander lust in their nature, will have a peaceful and pleasant domestic life. His wife will be religious, God fearing, law abiding and true. He will form friendship with new persons. In love affair, you will hardly succeed as you are in the nature of finding faults with others, rarely passionate, you postpone marriage and prefer to be bachelor, but when married you become home bird. Limited progeny, and will give them good education and will be worried about their future. All children will set well in life. The planetary signifier is Mercury.",
        weakness: "N/A",
        health:
          "Virgos enjoy a  robust health with long life and healthy old age. Active, look younger than age in youth. They are particular about their health. Stomach and nervous system are very sensitive, the use of much vitamin B in your diet will avoid these troubles and have regular meals. Avoid worries, discontentment, irritability and short temper.<br/>Normally you will have temptation for excess. High living and deep thinking should also be avoided. Be cautious against gall-stones. Avoid Alcohol and use vegetarian and balanced diet. Have plenty of rest and enjoy clam surroundings. When malefics are posited in Virgo, one suffers from dysentry, typhoid and sprue during this periods. You will have minor injuries very often and it is likely that you may meet with accidents, so do not drive rash. Virgo indicate bowels, kidney, large intestines, mesentery and nervous system, When lord of this sign Mercury is afflicted one can suffer from the above diseases.",
        cautions: "N/A",
        finances:
          "Being of a commercial instinct, you should be careful about your money. Hard work will pay you in life and bring you to top. Return of investment will be poor. If lord of 6th house, Saturn is exalted, receives good aspects denotes goods fortune.",
        loveAndMarriage:
          "Virgo born are very intelligent, so they find great difficulty in selecting the partner as they give more importance to intelligence than to pleasure and romance, but in a few cases, you will be disappointed. They are shy and not demonstrative in love. Do not be sensitive. As Virgos are in the habit of fault finding nature but passionate, they should try to appease others by conversation etc. You should bear in mind that as you require appreciation for your intelligence, so the people whom you love be praised and admired for their intelligence and beauty even if they do not possess these qualities.",
        husbands:
          "Virgos prefer to be bachelor for a long time as they treat married life a partnership or social scheme. But when married they provide all comforts to the partner and family members due to your wife, you will enjoy good family atmosphere and lead a happy life. Be not so economical that your married life becomes afflicted and this habit be avoided. Virgos have limited number of children and provide all facilities to them at any cost. Children will maintain good health and enjoy future. They may not show outer affection to the children.",
        idealMatch:
          "The persons born in Taurus, Capricorn and earthy signs and Cancer, Scorpio and Capricorn are best suited for Virgo born persons. Or the persons born on Mondays, Rohini (ৰোহিনী), Hastha (হস্ঠা), Sravana (শ্ৰাৱন) asterisms are suitable for happy and prosperous relations and partnership.",
        domesticEnviornments:
          "Change is your basic nature, wandering, change of residence and environments etc. Virgo people like an orderly home and put up a show when guests are invited. A good house, is always destined for you. Your wife will be religious and God fearing, law abiding and true due to which you will have a peaceful and pleasant domestic life.",
        professions:
          "Virgo born people should select their partners in business very carefully, who should keep them cheerful and utilise their intelligence as best, Virgo are slave to the work, hard taskmaster and like to be left alone in a quite place to carry out the work and plans. When Mercury forms good aspects shows the profession as a broker, accountant, lawyer, journalist, engineers, surgeons, work connected with liquids etc. Much depends on the planet forming good aspects with lords of 2nd, 6th or 10th houses in Virgo and be analysed accordingly.",
        lucky:
          "Lucky and favourable days are Wednesday, Friday, Monday and Thursdays whereas Sunday, Tuesday and Saturdays are not favourable for doing any important or auspicious work. Lucky numbers are 2, 3, 5, 6 and 7 whereas disagreeable numbers are 1 and 8 and the passive numbers are 4 and 9.<br/>Favourable and lucky stones are Emerald, Pearl, Diamond and Yellow Sapphire in gold which should be worn in 4th finger of right hand on Wednesday morning after offering prayers. But when Mercury is in fall or malefic Ruby and Emerald be used in Gold to minimise or ward off the evils. The day of fast is Friday throughout the life.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        warning:
          "A few of your friends and servants will betray you, will try to have your secrets, exploit them and may take you to court of law and stand witness against you to spoil you and your reputation etc. So you are warned to be careful from your servants and friends and choose them with great care. Better get their horoscopes checked before employing them or making them as friends.",
        traits:
          "Virgo born persons should not be so sensitive critical, conversationalist and chatty. Avoid too much calculating and in detail finding nature. Fault finding habit may be avoided. They should have self-confidence and avoid nature of changes. He should be a good judge and should not seek other's advice to often to confuse himself but stick to a single person's advice. Revengeful and long sustained resentment be avoided.",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Libra",
        asName: "তুলা",
        imageUrl: "libra.png",
        physicalAppearence:
          "Good complexion, well formed body, tall, slender in youth but tendency to stoutness in middle age, smooth, brown to black hair, blue or brown eyes, passionate, parrot like nose round or oval face, good features, curves and contours of body are regular, often have dimples, good looking graceful and youthful appearance with sweet smile and with attractive countenance. Almond eyes which speak themselves. Such persons look younger than age normally.",
        mentalTendencies:
          "Libran is fond of fine dress, perfumes, art and music. Fertile imagination and correct intuition, brilliant intellect, forethought, admirable refinement, supreme indemnity and pleasant nature.  Imaginative or artist, hopeful, cheerful, humane, just, orderly, sympathetic, loving but changeful, fond of society and amusements and usually amorous.  One can concentrate, meditate and reach a higher plane of spiritual life.",
        personality:
          "The planetary signifier is Venus. Librans are very courteous and hospitable, quick in temper which will soon be quietened. They are fond of beauty in all forms, easily appeased, enjoy always the society and company of brave, happy, sunny and mirthful people.<br/>Librans are affectionate, kind, generous and compassionate, idealistic, artistic, adoptable, constructive, intuitive, impressionable and inspirational, sexy, passionate and of compromising nature, so they become easily popular. Librans have such strong conjugal affection that they do not consider anything else more important than pleasure. Fond of opposite sex, argue with clarity and foresight. They have warmth and charming manners, take interest in their dress, make up perfumes, furniture, conveyance and other comforts. They are very affectionate and gentle, will be popular throughout the life. Full of charms and manners. Librans should keep their emotions in check, should not allow things to get out of hand. They should forgive but never forget. They must keep check on their expenditure as they are extravagant. Librans enjoy happy family life generally, also enjoy the life to the full. They are everlasting friends as they are honest in love, courteous and generous. Without friends they cannot pass life. They are expert in love affairs and they are sincere. They marry early in life, happy at home and in social life, sometimes they will have partners who cannot satisfy them, they cannot remain together for a moment. Librans have limited number of children, who will be helpful to them in old age. Generally Librans do not have such younger brothers who are as useful, reliable and true to them. They are more benefitted by a few sincere friends. Health and Diseases<br/>Librans enjoys good physical structure. But they are prone to infectious diseases. Kidneys, loins, spines, uterus, male's private parts, pineal glands and lumber vertebrae are the indicated body parts by Libra sing. So one can expect troubles in these parts. Appendicitis, lumbago and polyuria etc. are the diseases indicated.",
        weakness: "N/A",
        health: "N/A",
        cautions: "N/A",
        finances:
          "Since Librans excel other people in matters of reasoning, logic, foresight and judgement, their partners look to them for guidance and correct decision. Also good critics and suited for law so they are blessed with finance, wealth and good conveyance. Librans are extravagant, they spend on luxuries, dress, curios etc. They will donate for good causes, generous and liberal.",
        loveAndMarriage:
          "Librans are expert in love affairs, so they are most lovable people for sex life. Sincere and affectionate in love and their charming manners, dress, fashion etc., they attract the opposite sex. Their passions rise and die quickly. Librans enjoys most in the company of opposite sex, good debater. They marry early in life. Fond of life of amusement, social gatherings, happy at home and cheerful. They love high standard of living. Sometime they cannot have partner who can satisfy them.",
        husbands:
          "Librans are cheerful, romantic, passionate and of adjusting nature. They try to accommodate to a good extent. They will provide the family with all comforts, luxuries and necessities of life. Good expressive of love. In case they do not get response of love from their partner they become disappointed and do not seek divorce but try to adjust. Partner in life is indicated by 2,7 and 11th houses whose lords are Mars and Sun, so the partner in life will be of rash and short tempered and are of independent views. Mostly they will be Martians and Leos. So Librans has to tone down the fiery nature of partner with their diplomacy and tact to maintain peace at home.",
        idealMatch:
          "Librans are best suited to Gemini and Aquarius born, they will manage with others except Pisces, Capricorn and Cancer born people who will not agree with them.",
        domesticEnviornments: "N/A",
        professions:
          "Librans have much to do with government servants and officers, they will lead mostly a public life with both financial and social success. They do not hurt others, so they are popular. Best suited for law and may engage themselves in liquid items, also chemists, electrical engineers, transport, Navy and painters etc. Also they can be writers, musician, play back singers, architects, teachers and good salesmen.",
        lucky:
          "Lucky days are Sunday, Monday, Saturday, Tuesday and Wednesdays, whereas Thursday is evil and Friday offers mixed results. Lucky numbers are 1, 2, 4 and 7 whereas 5, 6, 3 and 9 are inharmonious. 8 stands for investment and profit to one with whom Librans transact. Lucky colours are orange, white, and red. Green and Yellow be avoided. Lucky stone is diamond in gold or platinum in 3rd finger on Friday morning after offering prayer. When Venus is in fall or unfavourable use white coral or white sapphire. Day of fast is Tuesday to mitigate or reduce the evils in life.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "Librans should control their emotional nature. Much of the time will be wasted in love and sex as they combine business and pleasure which should be avoided. Librans gain through fortune or good will, generosity of an affectionate and influential people or associates, so checking of their emotions is a must for them lest they go out of bound and allow things to go out of hand.They should not be extravagant, be decisive, avoid copying mannerisms from others. Being of liberal nature, they should not be fooled, and form the habit of forgiving but not forgetting. They should also learn say 'NO' to the people.",
        children:
          "Librans will have limited children, dutiful and helpful in old age. They take care of their children well. If children are born when Saturn is in Libra sign, then they will be renowned, diplomatic, obedient, peace loving, moderate, impartial, polite and submissive.",
        ladies: "N/A",
        friends: "N/A",
      },
      {
        name: "Scorpio",
        asName: "বৃশ্চিক",
        imageUrl: "scorpio.png",
        physicalAppearence:
          "Scorpions have good personality, well proportioned body, long hands, stature average, broad face, commanding appearance, short and curly hair and muscular body. Tendency to stoutness, often square type of face and robust build of body, prominent brows and dusky complexion unless ascendant is aspected by some malefic planets. ",
        mentalTendencies:
          "Scorpio sign represents the poisonous Scorpion. This sign represents two types. The higher type people who have control over their senses, others are lower type, will be jealous of others and rude, strong Willed but irreconcilable and are undefeatable and seekers of sensuous pleasure. So we can sum up Scorpions as quick, keen, shrewd, critical of penetrating mind and keen judgement. They are self reliant, bold and of fixed views being this a fixed sign. A subtle mind hard to influence, not easily imposed upon, energetic, courageous and sarcastic. A few are of practical nature. Scorpions are interested in occult, chemical research and in mystery. Self assertion, an extremist, have strong likes and dislikes, and have tendency to over ride and keep others under control. Scorpions are best detectives and fond of investigating mysteries and occult.<br/>They have intense feeling of emotions, blessed with power of intuition, quite resourceful, they enjoy life from lowest pleasures to highest tone. They are impulsive, forceful, have constructive and destructive ability, they can be frugal and economical, unyielding, and are self-made natives. They lose their temper quickly, get irritated and are highly sexed. Sometimes they get ill repute. They have rational thinking hate gossip, loose talk, black mailing and only concerned with their own work. They are free frank, plain and sarcastic. Cunning but very true, loyal, faithful and reliable. But in case others misbehave or become unfaithful etc., they become revengeful, relentless and selfish. <br/>Scorpions are lucky in case of finances and in anything they want like vehicles, wife, business, house, service, etc. but they cannot save the money. They do not want to remains under anybody's control but want to command others. Their domestic life is generally happy. They are good friends but also worst enemies, so lifelong friendship for them is not possible. They are violent but have complex moods. In love affair they are intense, dynamic and energetic. But to have a pleasant and smooth life with their wife and opposite sex in general, they must have sympathy, good understanding and steady affection and try to cultivate it. They want compliments and appreciation from their partners but cannot withstand with any criticism so one should be careful for marrying a Scorpio girl and check that her ascendant should not be afflicted.",
        personality:
          "Scorpions cannot remain idle, while facing obstacles and hindrances they are at their best talents, and never surrender but fight to the last end. They have fertile imagination Scorpio being a watery sign. Reserved, tenacious, determined and quick witted. Alert, forceful and positive. Often Scorpions are blunt, fond of contest and travel.",
        weakness: "N/A",
        health:
          "Scorpio denotes generative organs, Pelvic bone, bladder, enlargement of prostate glands, testicles and seminal vesicles. Jupiter Mars in Scorpio cause the diseases of above body parts whereas Saturn causes stone in bladder. 6th house is a house of disease which is Aries for Scorpio ascendant and indicates brain affliction, insomnia, neuroglia, coma, trance and somnambulism.",
        cautions: "N/A",
        finances:
          "Scorpions are lucky for wealth, also they gain through speculations, blessed with money, vehicles, wife, business or good position in service, house, garden etc. They are extravagant. Their income will be substantial as they know how to make and earn money.",
        loveAndMarriage:
          "Scorpion are intense, dynamic, energetic in romance and love but of complex moods, Unless Scorpions have sympathy, good understanding and steady affection and try to cultivate they cannot have a pleasant smooth life with opposite sex. They cannot tolerate any criticism, but provide full comforts to the wife. The wife of Scorpion will be just, honest, sincere and generally lucky. But when 2, 7 and 11th houses are occupied by malefic, difficulties arise in married life.",
        husbands:
          "Scorpion husbands will appreciate the qualities of their wives. He loves his wife, cares more for honour and family prestige. They are rash in temperament, of adjustable nature. A Scorpio husband should never marry a girl born in Scorpio with adverse aspects to lagna or ascendant and Mars, but if it receives good aspects or no bad aspects, one cannot get better wife than Scorpio born.",
        idealMatch:
          "Scorpio born suit well to people born in Scorpio, Pisces, Cancer, Virgo, Capricorn and Taurus. ",
        domesticEnviornments:
          "Your basic nature is to boss over others, so you like the same at home. You cannot lead the life without full comforts. Spend more than income. You want to design your home according to your taste. Face troubles boldly and convert them to you advantage. Scorpions are more successful and happy than others.",
        professions:
          "Scorpio indicates chemistry, medicine, insurance, maternity departments also surgeon, chemists, research work, C.I.D., detectives, iron and steel works, military and naval departments. Good and honourable professions will be occupied by Scorpions.",
        lucky:
          "Lucky days are Sunday, Monday, Tuesday, Friday and Thursday, whereas Wednesday and Saturdays are not favourable days. Lucky numbers in order are 3,9,4,1,2 and 7. Avoid 5,6 and 8.Lucky colours are Yellow, Red, Orange and Cream. Avoid Blue, Pure White and Green colours. Lucky stone is Yellow, Sapphire or dark Red Coral in gold or copper respectively in 4th finger on Tuesday morning after prayer. Also may use Ruby, coloured pearls for favourable results. But if Mars is afflicted or malefic use Ruby or Red coral plus Pearl in silver or copper in 1st or 4th finger as above. The day of fast is Tuesday for Success and prosperity.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "Scorpion should not be sarcastic, over critical, control their temper, try to avoid secret enmity of the ladies and be not selfish. Be patient and wait for the results of his efforts. It the bad side of Scorpio dominates then they are master of creating anarchy, lawlessness and destruction as they are then social fire brand and dangerous to the community. Do not fall prey to the habit of drinking. Revengeful nature be avoided.",
        ladies: "N/A",
        children:
          "Large family, but if Jupiter and Mercury are afflicted one may not have any child. The children will be lucky and intelligent. Scorpion can have friends for long time but if they choose any friend and maintain the same then the relations will last throughout life. Scorpions retaliate and are extremists. To gain from a Scorpion born person you should adjust yourself with him and then you can get a lot from him.",
        friends: "N/A",
      },
      {
        name: "Sagittarius",
        asName: "ধনু",
        imageUrl: "sagittarius.png",
        physicalAppearence:
          "A well proportioned and a well developed body. Tall, slender, generally long or oval face, large forehead, high or bushy eyebrows, long nose, bright expressive blue or hazel eyes, clear complexion but subject to aspect of other planets. Charming appearance, graceful look and handsome figure. Brown or chestnut hair inclining to baldness especially near the temples.",
        mentalTendencies:
          "Generous, bold, good hearted, ambitious, greedy and aspiring, good tempered, just, frank, free, cheerful, charitable and friendly. They look to the bright side of the things, dauntless with self-confidence. Active and enterprising, sympathetic, humane and somewhat impulsive. Fond of travelling, voyage and outdoor sports and exercises. During obstacles, they are at their best. Blessed with energy, enthusiasm, vigour and vitality. Sagittarians are inclined to philosophy, law, medicine or religion.",
        personality:
          "Sagittarians are not timid, they will not flutter nor fear and tremble even in adverse conditions. Act after deep consideration, jovial, hopeful, generous and charitable. Love, liberty, independence and freedom, also they are good humoured and honourable. They are frank, fearless, demonstrative, out spoken, nervously. They are frank, fearless, demonstrative, out spoken, nervously energetic, ambitious, sincere and quick. Love, truth, have desire to develop friendship with foreigners. God fearing and religious. They are blended with power of intuition and prophetic. At times they are restless, over anxious and highly strung. Respectful to religion, law and order and customs. They are in profession, aggressive, progressive and aspiring, quick to see end take the advantage if situation and opportunity. They are always outspoken, to the point, straight and directly hit the mark. They try to get higher education and fond of travel, cannot remain under the control of others. Professions suitable to them are the company law, civil engineering, contractor, work in foreign embassy or in foreign affairs. Speculation is always detriment to them.<br/>Sagittarians should not insult or hurt others by giving their frank opinion. Do not develop hatred towards your brothers and parents, this will not pay you. You will be liked by your friends and will be generous to the opposite sex and friendly with them. At home you may not be successful and enjoy the independence which you desire, so be of adjustable nature.",
        weakness: "N/A",
        health:
          "Sagittarius governs the hips, thighs, lions, buttocks, glutinous muscles, Sacral Arctic’s, etc. So the diseases indicated are gout, rheumatic pain, hip fracture, lung troubles. Mars and Saturn in Sagittarius causes fracture of bones and also ulcer in the thigh needing surgeon's help or operation. Also one may suffer from gout and pulmonary apoplexy. Jupiter in ‘Poorvashada’ star causes diabetes, Saturn alone indicates contusions of hips, T.B. asthma etc. Moon indicates bronchitis, pneumonia, diabetes. Sun causes poor vision, a defective hearing, Venus indicates tumor, diabetes etc. Mercury shows hiccough asthma etc. and also causes fatal diseases being also a lord of Bhadhaka Sthana adhipathi. Generally Sagittarians enjoy good health.",
        cautions: "N/A",
        finances:
          "Sagittarians like frequent changes, to work with free hand rather to be ordered to do, nor they prefer to sit tight at one place and work. They are rich with full comforts of life quickly and have gains without pains. If Jupiter is not afflicted politics will prove lucky.",
        loveAndMarriage:
          "The married life of Sagittarians is generally happy and prosperous. They make friendship with all due to their sweet smiles and quick wit, liked by wife and friends. They are not fond of home but are much interested in outdoor life. They take much interest in children as age advances, you should not curb their independence lest they become obstinate and strong willed. Blessed with good wife. The Sagittarians must be very tactful in dealing with their children.",
        husbands:
          "Sagittarians flare up quickly and last for a short time. Fond of games, sports and clubs and these are important to him rather than family life. They are persons of morality and dignity, the maturity will come late in life. They maintain integrity. Will be blessed with a good wife, particularly when one marries a Sagittarians girl who will be modest and polite and will be lucky.",
        idealMatch:
          "Sagittarians suit best to Sagittarians, and Gemini born persons. Also best suited for Arians and Leos, they will have better understanding with Librans and Aquarians.",
        domesticEnviornments:
          "Generous and friendly with opposite sex whereas they do not like relatives, spend much on children. Also charitable, religious and attached with educational institutions. At home they are failure, if are denied independence which is their basic nature to have.",
        professions:
          "You can be a good teacher, preacher, public speaker, bank employee, politics will suit you best 21st attached with religious and educational institutions. Also editing and publishing will be rewarding. You may master company law, civil Engineering, contractor, foreign assignments, but speculation will not be helpful and profitable.",
        lucky:
          "Lucky days are Wednesday, Friday, Thursday and Sundays, whereas Monday will cause anxiety and troubles, Tuesday loss and extravagant expenses and Saturday indicates slow, steady progress and assistance from others. Lucky or favourable numbers are 6,3,5 and 8. Avoid 2,7 and 9. The numbers 1 and 4 will be passive. Lucky colours are white, cram, green, orange, light blue, and emerald. Avoid red, pearly and black. Lucky stones are Topaz in Gold in first finger of right hand on Thursday morning after prayer. When Jupiter is afflicted or unfavourable yellow sapphire plus red coral. All above stones should be used in gold. Day of fast. Thursday.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "Be moderate and do not hate your relatives, parents and brothers. Exaggeration and continuous speech without truth, false promises, insulting or hurting others are your basic traits which be avoided. Your behaviour will be inconsiderate at times. Care for your family in addition to outdoor activities. Do not be of vindictive mind. You have nature of disturbing others in unnecessary way and you change your opinion often which needs correction.",
        ladies: "N/A",
        children: "N/A",
        friends: "N/A",
      },
      {
        name: "Capricorn",
        asName: "মকৰ",
        imageUrl: "capricorn.png",
        physicalAppearence:
          "Prominent features usually thin and long, long or prominent nose, thick neck, long chin, dark or black hair, thin beard, usually not very handsome stature short in early age but one grows tall suddenly after 16 years of age. The constitution improves with age as it will be slender in early age. The person will become hunchbacked as the age advances. There will be a scar in the knee cap or at least a mole. Generally defective walk and liability to rheumatism in the joints.",
        mentalTendencies:
          "Capricorns are economical, prudent, self-willed, reserved, pensive, reasonable, thoughtful and of practical nature. They are calculative and business like. Secretive, quite, much mental ingenuity and fertility, changeable, capricious and will have push and confidence. Desirous of wealth, power and authority, ability for managing and organizing. They are also methodical and plodding.",
        personality:
          "Capricorn being a movable sign, one will execute quickly any work after taking a careful decision. When it is found advantageous, one will not hesitate to change his career. He will have special organising capacity and with good tolerance, patience and steady nature. Serious, quite, thoughtful, contemplative nature, possessing dignity and self-esteem. Also one is cautious, hard worker, capable, of much endeavour, able to plan and carry out schemes of considerable magnitude and will be at the head. He will not depend on the hopes of others, not demonstrative in feeling and do not readily show his sympathy. It is not easy to cheat him, modest and polite, he can make friendship with anybody quickly but he will make test of an individual and finally make a permanent tie of friendship.<br/>Capricorns are self reliant, thrifty, respectful to religion, interested in theology, either honest, sincere or reliable or the most conceited, dishonest, selfish, greedy, miserly, never hesitate to commit any crime when Saturn, the signifier is much afflicted in birth chart. They will rise gradually will make repeated attempts and will finally come out successful. They will utilise everything to a material purpose.",
        weakness: "N/A",
        health:
          "Capricorns should be in cheerful youngsters, take hot and stimulating food and laxatives. They should do regular exercises, never jump and fall down, this will lead them to good health. Capricorns are depressed and discontented, worried and gloomy, gradually the digestive system will become weak and may cause flatulence. The diseases indicated are injury to body parts, to knee cap, skin disease, eczema, dislocation, hysteria, rheumatic and pulmonary. Saturn in Uttrashada star indicates heart palpitation whereas Mars indicates cardiac thrombosis, Rahu and Ketu cause blood pressure. Planets in Dhanishta denote high fever, bronchitis, pneumonia, fracture and dislocation etc. Mars, Saturn and Moon are not good for longevity in their conjoined sub periods in the major period of evil planets.",
        cautions: "N/A",
        finances:
          "Capricorns are desirous of name, fame, money and reputation. They are conservatives, will not mind difficulties, handicaps and hindrances, but will work continuously to gain success. They do not miss any chance and opportunity and do not speculate. They have value of money and will invest carefully and save slowly and steadily. They are economical, trustworthy, wide awake and they do not take risk they do not expect a windfall.",
        loveAndMarriage:
          "Capricorns are not emotional, but slow and cautious in approaching opposite sex, not bold and rash and never take lead, opposite sex remains worried by the hesitancy of the man born in Capricorn. They take long time to choose a partner. They may have affection but are not demonstrative in love and not fit for romance, dance etc.",
        husbands:
          "Capricorns husbands are not romantic yet they provide full comforts to the family in slow and steady way. Choosy about partner and do not take any body in confidence, they have many acquaintances but less real friends to whom they will be true and respect them throughout life. An active member of clubs and societies. They are slow in passions and afraid to proceed further unless obtain consent thrice and in a sure way.",
        idealMatch:
          "Capricorns are best suited for Scorpio, Cancer and Pisces born persons. Also persons born on Tuesdays, or in Mrigasira, Chitra and Dhanishta nakshatras will be helpful. Persons born in Rohini, Poorvaphalguni and Poorvashada stars are very helpful.",
        domesticEnviornments:
          "They are anxious for early marriage, but are destined to marry. They will be dutiful to the children and family, but will not display their love. Keep the home beautiful, hate noise and like clam atmosphere and privacy, seclusion and peace. Care most for respect and prestige of the family.",
        professions:
          "When Moon forms good aspects with ascendant and lord of ascendant, she indicates business of kerosene oil, land and animals, contractor in irrigation department and a successful agriculturist. Mars forming favourable aspects denotes engineer, cement manufacturer, lawyer, brick kiln owner, Mercury indicates engineers, deep thinker, dealers in scientific instruments, crystal grazing. Yoga are advantageous. Jupiter forming good aspects denoted physician or scientist, gain through large companies, clubs and societies. Also through land and mine products, long term contracts etc. Venus indicates chemicals, leather and hides, religious head, Sanyasi etc.",
        lucky:
          "Lucky and favourable days are Friday, Tuesday, Saturday and Wednesdays whereas Sunday, Monday and Thursday are days of worries and expense. They should speculate on Tuesday and Friday. Invest on Saturday, sign documents contracts etc. on Tuesdays. Lucky numbers are 6,9,8. Avoid 3, other numbers are passive. Favourable colours are white, black, red and blue. Avoid yellow and cream colours. Lucky stone is blue sapphire and be used in gold or five metals ring in 2nd finger of right hand on Saturday morning after prayer. But when Saturn is in fall or unfavourable, use blue Sapphire plus red Coral or Blue Sapphire plus emerald as above. Day of fast for good luck is Saturday.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "The native should correct his following defects and faults when lagna or lord of lagna Saturn are badly aspected: 1. One should not be selfish, egoistic, pessimistic. 2. He should not become desperate and broken hearted. 3. One should not over work and exert too much but also take rest to maintain his health. 4. He should not overstrain and feel fatigued.5. He should develop dignity and diplomacy, avoid nervousness and discontent. <br/>They should develop dignity, diplomacy, avoid nervousness and discontent. If ascendant or Saturn receives bad aspects from any planet, the native will be mostly selfish and egoistic pessimistic, desperate and broken hearted. They will work hard and over exert, contemplate mediate and tax himself much and due to overstrain will be fatigued. All these traits are required to be corrected.",
        ladies: "N/A",
        children:
          "Capricorns have number of children but will not mix with them, and not allow them to go beyond limit, keep them under control, but will not antagonize them. Children will be more affectionate as age advances.",
        friends: "N/A",
      },
      {
        name: "Aquarius",
        asName: "কুম্ভ",
        imageUrl: "aquarius.png",
        physicalAppearence:
          "No doubt that this sign is of short ascension yet the people born under this sign are tall with full stature. Strong, well-formed, tendency to stoutness in middle age, good, clear complexion, oval face, handsome appearance, brown shade hair, mole or scar on calf-muscles. Fleshy face good looking and friendly countenance. ",
        mentalTendencies:
          "Intelligent, good memory and reasoning faculty. Very capable of dealing with facts, possess good concentration, kind, humane, self-controlled. Constant, preserving, happy disposition, inventive and also psychic. Have many friends. Can read other's characters, broad outlook and like solitude. They often become physicians.",
        personality:
          "Aquarians are serious, quite, thoughtful and of contemplative nature. Defective teeth, intelligent, cautions, prudent, economical and practical. Outspoken, unselfish, humane and impersonal. They are very social but very choosey about friends. Hard workers, have organising capacity, of profound thoughts, also shrewd, clear headed, quick-witted and wide awake. Blessed with new and fresh ideas, use own thinking and discretion, originate new ideas.<br/>Will do all things which are morally right. They have their own individually and speciality. Constant in friendship, stick to a principle. Best fitted for research and Physics. Aquarians are strong in their likes and dislikes. Stubborn but not fool hardy. they develop intuition and good concentration. They do not preach others but act themselves. They observe fast, penance etc. and sound financial position. Aquarians are prone to infectious diseases. Cannot withstand cold, they should attend immediately to an injury, should not overtax themselves and take plenty of rest. Venus is Badhaka Sthana whereas Jupiter and Sun are Maraka planets.<br/>Honour, wealth come to them. But they are both fortunate and unfortunate. They are neither very much attached nor detached with their family. Gemini and Libra born ladies are best suited as their partners. They will have good children The result indicated for Aquarius ascendant are firm and general for the different planets in the different houses. They are to be suitably modified. according to the aspects and conjunction with other planets.",
        weakness: "N/A",
        health:
          "Aquarians are susceptible to infections diseases. One should not overtax oneself but take rest. The heart may cause trouble, it may be rheumatic or cause blood pressure. Tooth, throat and tonsil, swelling of legs, ankles feet and left ear troubles are also denoted. One may suffer from eye troubles. One should immediately consult a doctor in the case of even a minor trouble or ailment and one will recover from them when the disease is as indicated by Moon, but the diseases caused by Jupiter, Sun, Mercury and Venus in their conjoined period or sub period will be fatal. Moon causes dropsy and common ailments during its period being a lord of 6th house and planets posited in Dhanishta threatens high fever, malaria, high blood pressure fractures etc. Whereas planets in Satbhisha causes poor digestion or one suffers from constipation, blood pressure and insomnia. Planets in Poorvabadhra produce dropsy, defective blood circulation eczema, skin troubles, ulcerated gums etc. Venus is Bhadhaka-Sthana Adhipati Lords of 2nd and 7th are Maraka Sthana adhipatis, they are Jupiter and Sun which affect longevity.",
        cautions: "N/A",
        finances:
          "Honour comes to them, Aquarians never seek them. They are both fortunate and unfortunate. They work hard and wait patiently for some development and novel results and then only expect money. To money, they consider, that it is only needed for worldly life.",
        loveAndMarriage:
          "Aquarians are intelligent and always prefer educated and equally intelligent partners. They move with all very freely but with those who are social equals they are shrewd and studious. They prefer permanent and strong attachments. They are unassuming, they do not boss over the partner. In case the person is not unto their standard they may slowly and without assigning any reasons discontinue the love relations and friendship. Aquarians do not show love and are cold, so the partners if are passionate they will not be satisfied. The partners will be law biding, true, honest and sincere, dutiful, magnanimous and noble. They care peace, harmony and happiness. Those who marry Aquarians, find them very humane, kind, sympathetic and accommodative and generous and gracious.",
        husbands:
          "Aquarian husbands are intelligent and ever think and carry research in science etc. so they have little time to pay full attention to the wife and family and may not be taken as a drawback and lack of interest to such wives who are selfish. Otherwise they are very humane, kind, sympathetic, accommodative, generous and genius. They are harmonious husbands contributing for happy life. They are strict teachers and treat their children as grown up individuals who are respectful and affectionate to the parents. They educate them and encourage them to be bold and expressive. They become clever and versatile, but expect respect from them.",
        idealMatch: "Aquarians can suit best to Gemini and Libra born persons.",
        domesticEnviornments:
          "Aquarians are very social, they keep the home clean and tidy, well furnished, modern fashionable home. Fond of entertaining friends and collecting more and more antiques. They are in the habit of adaptability. Unconventional but adopt modern methods to save time and trouble. They prefer society and solitude, more dutiful to their relatives, they are neither much attached nor detached.",
        professions:
          "2nd house lord Jupiter indicates the professions for Aquarians can be scientist, good executive, position in large office or concerns, a lecturer, astrologer, legal, financial or education advisor. Mine contractor, or dealer in shipping and export.6th house lord Moon indicates one may practice in medicine, social service, shipping, sailor, submarine, pump set dealer, export and import business of liquids.10th house lord Mars denotes the professions of building construction, chemicals, mechanical engineering, brick kiln owner, cement dealer, surgeon, dealer in lead, copper and steel or C.I.D. officer.<br/>The professions will also be of the planets forming good aspects with cusps of 2nd, 6th and 10th houses.",
        lucky:
          "Thursdays, Friday, Tuesday and Mondays are favourable and lucky days. Wednesdays and Saturday are unfortunate whereas Sunday offer mixed results. Lucky Colours. Yellow, Red, White and Cream are lucky and favourable colours. Avoid orange, green and blue. Lucky Numbers. Favourable and lucky numbers 3, 9, 2 and 7. But unfavourable number are 1, 4, 5 and 8. Passive number is 6.Lucky Stone. Blue sapphire is lucky stone for Aquarians and should be used in gold or in five metals ring and be worn in 2nd finger of right hand on Saturday morning after offering payer. In case Saturn in unfavourable or afflicted one should use Blue Sapphire, Red Coral or Blue Sapphire plus Emerald as above.",
        gemstoneWarning: "N/A",
        traits:
          "If either the ascendant or Saturn, the lord the ascendant , is afflicted by the adverse aspect from any planet. 1. The native will be lazy and lethargic, and hence he should cultivate activity, promptness etc. 2. He should avoid solitude. 3. He should not be worried, gloomy and pessimist. 4.He should be pushy and alert. 5. He should not be very rigid towards those whom the Aquarians dislike.",
        ladies: "N/A",
        children: "N/A",
        friends:
          "Aquarians are always lively, good humorous, high spirited and cheerful. They want many friends, and are almost reliable, sincere and good but with some of them they might be somewhat reserved. They are not in habit of finding fault with others but take everything easy. Good partners in business. They should be careful for selection of friends and some of them may not be selfish or cheat and so avoid too much intimacy with others and all Aquarians should be quiet and unassuming which will enable them to make a large number of friends and make the home pleasant.",
      },
      {
        name: "Pisces",
        asName: "মীন",
        imageUrl: "pisces.png",
        physicalAppearence:
          "Pisceans are generally of short stature, of plump body, short limbs, full of fleshy face, pale complexion, tendency to double chin, muscular and spherical shoulders. Big and protruding eyes, soft and silky hair. Wide mouth and inclining to corpulence especially in later years.",
        mentalTendencies:
          "Quick in understanding, inspirational, versatile, easy going, good natured, changeful, psychic, emotional, fond of music, passionate, affectionate and charitable. Sometimes they are secretive, reserved or mysterious in their way of doing things. Philosophical and lead a romantic life.",
        personality:
          "Kind, loving, truthful and of sympathetic nature. Courteous and hospitable. Restless, helpful and humane. Lacking generally in self-confidence, self-esteem, modest, timid, and they cannot harm anyone. Being dual sign Pisceans are puzzle to others and to himself even, cannot be steady, mostly sweet tempered and social. Led away by fancies and new ideas, polite and modest. At times they are over anxious and become disheartened, indecisive and lacking in life and energy. They use best of circumstances, vital temperament. Of varying moods, over liberal, keep hopes on other's promises, rely friends and many a times suffer at their hands. Addicted to drink, love psychic and occult science. They are best suited as poets, musicians, in planning commission, painters, nurses, caterers, teachers, accountants, banker, actors or as Liaison officers etc. Pisceans should marry for happy married life to persons born with Virgo and Cancer ascendants.",
        weakness: "N/A",
        health:
          "Being a watery sign one will be addicted to drink. the persons will suffer from gastric troubles, varicose veins or guinea worms. Affliction of bile and feet is denoted. This sign governs ankle, feet, teeth and left eye and the diseases indicated are consumption, tuberculosis, tumours and mucous troubles. Planets in Poorva Bhadra constellation shows abdominal tumour, enlarged liver and enzymes deficiency and in Rewati star causes deafness, general nervous debility, cramps, etc. Sun in Pisces produces perspiration of feet, chillness, intestinal troubles due to lack of blood supply and typhoid. Moon denote drink, over drugging the system. Mars indicates fracture in the foot, deformities, a piles, inflammation in the bowels and hernia. Mercury causes nervous debility, deafness and tuberculosis. Jupiter in Pisces denotes swollen feet, perspiration, enlargements of liver, abdominal tumours, deficiency of enzymes and intestine troubles. Venus causes gout, intestinal troubles whereas Saturn causes Rheumatism, foot-droop, tuberculosis and dropsy.",
        cautions: "N/A",
        finances:
          "Pisceans have food business ability. They are endowed with wealth and power. They do not relish the idea of being dependent on their children. In old age so they keep the money safe for that period. They are helpful to needy person and make advances of money to those who can repay on demand. They have plurality of interests.",
        loveAndMarriage:
          "Pisceans will remain attracted to the romantic life, prefer beauty of the partner and intellect. Suspicious by nature towards partner which kills their love but they like flattery. They should not select any partner who is free with all. Since Pisces is dual sign, the person will be affectionate but reluctant at times whereas in other moments they will be amorous and affectionate. Will lead a happy married life. Such persons are kind, sympathetic, and loyal. Good and moody persons. Bold, brave and independent. They love their children who are also affectionate and successful in life.",
        husbands:
          "Pisceans husbands are affectionate, kind and full of love but suspicious by nature. For a happy and prosperous married life they should not doubt the partner. Throughout their life they will be attracted towards romantic side. Very helpful and maintain harmony at home. Sincere and true.",
        idealMatch:
          "Pisceans are best suited to Virgo and Cancer born persons. ",
        domesticEnviornments:
          "Pisceans have many friends and are happy to entertain them at home, wish to have educated partner in life and have good children. They love happy domestic life and are very affectionate. Throughout their married life they do not get tired to carry out the romantic legend of lovers. Tempted to fancies of life and with every pretty face and their fancies will be wanderings.",
        professions:
          "Pisceans can be successful as accountants, bankers, music and opera houses, cinema, occult sciences, actors and a good business ability and can be a successful liaison officer, Managing Director or Chairman. Best suited for Navy Shipping Corporation etc. deals in drinks, oils, beverages, cosmetics, chemicals, medical and education departments. Pisceans cannot concentrate and do hard work. But if they are compelled to do then as they are methodical, persevering, industrious, true, sincere and honest. The professions connected with Saturn will result in loss and be avoided.",
        lucky:
          "Sundays, Tuesdays and Thursdays are favourable and lucky days. Mondays and Saturdays will cause loss and unfavourable also the Wednesdays and Fridays will not be harmonious fruitful. Lucky Colours. Red, Yellow, Rose and Orange are favourable. Avoid Blue. For partners prosperity, the partner should use White, Cream and Green. Lucky Numbers. Favourable and lucky numbers are 1, 4, 3 and 9. Avoid 8, other numbers are passive. Lucky Stones are Topaz or Pukhraj in Gold be used in first finger of right hand on Thursday morning after prayers. When Jupiter is malefic or unfavourable use of white pearl in silver or yellow sapphire plus red coral is recommended for use to minimise and avoid the evils and difficulties.",
        gemstoneWarning:
          "Consult good astrologer for Gemstone, birth sign is not enough to recommend gemstone.",
        traits:
          "Pisceans should not rely upon all their friends, must be choosy about them as they all will not be sincere. The friends, a few of them, will outwardly be honest but inwardly scoundrel, cheat and selfish. Avoid suspicious nature and varying moods. Cultivate push, be generous but not over liberal, do not be contemplating and dreaming always and they should not entertain and rely on other's promises.",
        ladies:
          "Piscean born ladies are beautiful, of big and protruding eyes. They will have tendency to flatulence as age advances. Romantic and passionate. Ladies are over liberal and have nature of unbounded generosity which should be avoided by them lest they fall victim of bad social elements and ruin their life. She cannot be steady in her love. They are sweet tempered, very social, polite and modest and can easily be led away by fancies and fresh ideas. They keep the home modern and in a top condition. They love domestic life on the whole.",
        children: "N/A",
        friends:"N/A"
      },
    ],
  };
};
